[server]
headless = true
runOnSave = true
maxUploadSize = 5

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#0f3460"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8f9fa"
textColor = "#2c3e50"
font = "sans serif"

[client]
showSidebarNavigation = false
